### ISSUE TITLE
Hugo live road map

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10939]
A lot of the work below is in progress, some of it is nearly done. These will be completed in the order given below.

- [x] Consolidate all configuration into one struct for documentation (and `hugo config` output), make it so a complete reference can be autogenerated. rewrite CLI. 
- [x] Tailwind 3 support[^1]. 
- [x] The "million pages" release.
- [ ] Pages from other data sources (including relevant plugin support)

[^1]: I, @bep, really need this. This somehow ties a little into the "million pages" branch, which much improves the detection of "what changed" when running a server, but we need to get a working setup sooner rather than later, and it shouldn't be that hard.
